-- Migration: Create normalized PDS child tables
-- Run on wpu_faculty_system

CREATE TABLE IF NOT EXISTS pds_children (
  id INT AUTO_INCREMENT PRIMARY KEY,
  pds_id INT NOT NULL,
  name VARCHAR(255) NOT NULL,
  dob DATE NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (pds_id) REFERENCES faculty_pds(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS pds_education (
  id INT AUTO_INCREMENT PRIMARY KEY,
  pds_id INT NOT NULL,
  level VARCHAR(100),
  school VARCHAR(255),
  degree VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (pds_id) REFERENCES faculty_pds(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS pds_experience (
  id INT AUTO_INCREMENT PRIMARY KEY,
  pds_id INT NOT NULL,
  dates VARCHAR(100),
  position VARCHAR(255),
  company VARCHAR(255),
  salary VARCHAR(100),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (pds_id) REFERENCES faculty_pds(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS pds_voluntary (
  id INT AUTO_INCREMENT PRIMARY KEY,
  pds_id INT NOT NULL,
  org VARCHAR(255),
  dates VARCHAR(100),
  hours VARCHAR(50),
  position VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (pds_id) REFERENCES faculty_pds(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS pds_learning (
  id INT AUTO_INCREMENT PRIMARY KEY,
  pds_id INT NOT NULL,
  title VARCHAR(255),
  dates VARCHAR(100),
  hours VARCHAR(50),
  type VARCHAR(100),
  conducted_by VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (pds_id) REFERENCES faculty_pds(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS pds_references (
  id INT AUTO_INCREMENT PRIMARY KEY,
  pds_id INT NOT NULL,
  name VARCHAR(255),
  address VARCHAR(500),
  phone VARCHAR(100),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (pds_id) REFERENCES faculty_pds(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Optional indexes
CREATE INDEX IF NOT EXISTS idx_pds_children_pds ON pds_children(pds_id);
CREATE INDEX IF NOT EXISTS idx_pds_education_pds ON pds_education(pds_id);
CREATE INDEX IF NOT EXISTS idx_pds_experience_pds ON pds_experience(pds_id);
CREATE INDEX IF NOT EXISTS idx_pds_voluntary_pds ON pds_voluntary(pds_id);
CREATE INDEX IF NOT EXISTS idx_pds_learning_pds ON pds_learning(pds_id);
CREATE INDEX IF NOT EXISTS idx_pds_references_pds ON pds_references(pds_id);

-- End migration
